version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: book-booking
      POSTGRES_USER: bb
      POSTGRES_PASSWORD: bb
    ports:
      - "5432:5432"