services:
  db:
    image: postgres
    container_name: book-booking-postgres
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_DATABASE}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-database:/var/lib/postgresql/data

  app:
    image: openjdk:21-jdk-slim
    container_name: book-booking-spring-boot
    working_dir: /app
    volumes:
      - ./build/libs/nnpro-book-booking-0.0.1.jar:/app/app.jar
    command: [ "java", "-jar", "/app/app.jar" ]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${SPRING_DATASOURCE_DATABASE}
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env

  js:
    image: node
    container_name: book-booking-node-react-vite
    working_dir: /react
    volumes:
      - ./src/main/react:/react
      - node-modules:/react/node_modules
    command:
      sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  postgres-database:
    name: postgres-database
  node-modules:
    name: node-modules