package cz.upce.nnpro.bookbooking.components;

import cz.upce.nnpro.bookbooking.dto.RequestOrderDTO;
import cz.upce.nnpro.bookbooking.dto.RequestPurchaseDTO;
import cz.upce.nnpro.bookbooking.entity.AppUser;
import cz.upce.nnpro.bookbooking.entity.Book;
import cz.upce.nnpro.bookbooking.entity.Review;
import cz.upce.nnpro.bookbooking.entity.Role;
import cz.upce.nnpro.bookbooking.entity.enums.GenreE;
import cz.upce.nnpro.bookbooking.entity.enums.RoleE;
import cz.upce.nnpro.bookbooking.service.*;
import jakarta.annotation.PostConstruct;
import lombok.AllArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

@Component
@AllArgsConstructor
public class DatabaseRunner {

    private final RoleService roleService;

    private final UserService userService;

    private final BookService bookService;

    private final ReviewService reviewService;

    private final OrderService orderService;

    private final PurchaseService purchaseService;

    private final PasswordEncoder passwordEncoder;

    @PostConstruct
    private void init() {
        initRoles();
        initUsers();
        initBooks();
        initBookings();
        initPurchases();
        initReviews();
    }

    private void initRoles() {
        roleService.create(new Role(RoleE.ADMIN));
        roleService.create(new Role(RoleE.USER));
    }

    private void initUsers() {
        userService.create(new AppUser("Běžný",
                                       "Uživatel",
                                       "user@email.cz",
                                       "user",
                                       passwordEncoder.encode("user"),
                                       roleService.getByName(RoleE.USER)));
        userService.create(new AppUser("Pověřený",
                                       "Admin",
                                       "admin@email.cz",
                                       "admin",
                                       passwordEncoder.encode("admin"),
                                       roleService.getByName(RoleE.ADMIN)));
    }

    private void initBooks() {
        List<Book> books = Arrays.asList(new Book("The Hobbit",
                                                  "J.R.R. Tolkien",
                                                  GenreE.FANTASY,
                                                  "A fantasy novel about the adventures of Bilbo Baggins.",
                                                  true,
                                                  true,
                                                  true,
                                                  7,
                                                  7,
                                                  12.99),
                                         new Book("1984",
                                                  "George Orwell",
                                                  GenreE.DYSTOPIAN,
                                                  "Dystopian novel about totalitarianism.",
                                                  true,
                                                  false,
                                                  false,
                                                  5,
                                                  5,
                                                  0.0),
                                         new Book("Pride and Prejudice",
                                                  "Jane Austen",
                                                  GenreE.CLASSIC,
                                                  "A romantic novel that critiques the British landed gentry.",
                                                  true,
                                                  false,
                                                  false,
                                                  4,
                                                  4,
                                                  0.0),
                                         new Book("The Great Gatsby",
                                                  "F. Scott Fitzgerald",
                                                  GenreE.CLASSIC,
                                                  "A novel about the American dream and disillusionment.",
                                                  true,
                                                  true,
                                                  true,
                                                  6,
                                                  6,
                                                  10.99),
                                         new Book("To Kill a Mockingbird",
                                                  "Harper Lee",
                                                  GenreE.DRAMA,
                                                  "A novel about racial injustice in the Deep South.",
                                                  true,
                                                  false,
                                                  true,
                                                  3,
                                                  3,
                                                  0.0),
                                         new Book("The Catcher in the Rye",
                                                  "J.D. Salinger",
                                                  GenreE.CLASSIC,
                                                  "A novel about teenage angst and alienation.",
                                                  true,
                                                  false,
                                                  true,
                                                  2,
                                                  2,
                                                  0.0),
                                         new Book("Moby Dick",
                                                  "Herman Melville",
                                                  GenreE.CLASSIC,
                                                  "A novel about the quest for revenge against the white whale.",
                                                  true,
                                                  true,
                                                  true,
                                                  1,
                                                  1,
                                                  9.99),
                                         new Book("Brave New World",
                                                  "Aldous Huxley",
                                                  GenreE.DYSTOPIAN,
                                                  "A novel about a futuristic society and its challenges.",
                                                  true,
                                                  false,
                                                  true,
                                                  5,
                                                  5,
                                                  0.0),
                                         new Book("Harry Potter and the Sorcerer's Stone",
                                                  "J.K. Rowling",
                                                  GenreE.FANTASY,
                                                  "The first book in the Harry Potter series.",
                                                  true,
                                                  true,
                                                  false,
                                                  10,
                                                  10,
                                                  14.99),
                                         new Book("Harry Potter and the Chamber of Secrets",
                                                  "J.K. Rowling",
                                                  GenreE.FANTASY,
                                                  "The second book in the Harry Potter series.",
                                                  true,
                                                  true,
                                                  false,
                                                  10,
                                                  10,
                                                  14.99),
                                         new Book("Harry Potter and the Prisoner of Azkaban",
                                                  "J.K. Rowling",
                                                  GenreE.FANTASY,
                                                  "The third book in the Harry Potter series.",
                                                  true,
                                                  true,
                                                  false,
                                                  10,
                                                  10,
                                                  14.99),
                                         new Book("Harry Potter and the Goblet of Fire",
                                                  "J.K. Rowling",
                                                  GenreE.FANTASY,
                                                  "The fourth book in the Harry Potter series.",
                                                  true,
                                                  true,
                                                  false,
                                                  10,
                                                  10,
                                                  14.99),
                                         new Book("Harry Potter and the Order of the Phoenix",
                                                  "J.K. Rowling",
                                                  GenreE.FANTASY,
                                                  "The fifth book in the Harry Potter series.",
                                                  true,
                                                  true,
                                                  false,
                                                  10,
                                                  10,
                                                  14.99),
                                         new Book("Harry Potter and the Half-Blood Prince",
                                                  "J.K. Rowling",
                                                  GenreE.FANTASY,
                                                  "The sixth book in the Harry Potter series.",
                                                  true,
                                                  true,
                                                  false,
                                                  10,
                                                  10,
                                                  14.99),
                                         new Book("Harry Potter and the Deathly Hallows",
                                                  "J.K. Rowling",
                                                  GenreE.FANTASY,
                                                  "The seventh and final book in the Harry Potter series.",
                                                  true,
                                                  true,
                                                  false,
                                                  10,
                                                  10,
                                                  14.99),
                                         new Book("The Da Vinci Code",
                                                  "Dan Brown",
                                                  GenreE.MYSTERY,
                                                  "A mystery thriller novel that involves art and history.",
                                                  true,
                                                  false,
                                                  true,
                                                  8,
                                                  8,
                                                  0.0),
                                         new Book("The Girl with the Dragon Tattoo",
                                                  "Stieg Larsson",
                                                  GenreE.MYSTERY,
                                                  "A mystery novel about a journalist and a hacker.",
                                                  true,
                                                  false,
                                                  true,
                                                  9,
                                                  9,
                                                  0.0),
                                         new Book("The Shining",
                                                  "Stephen King",
                                                  GenreE.HORROR,
                                                  "A horror novel about a haunted hotel.",
                                                  true,
                                                  false,
                                                  false,
                                                  6,
                                                  6,
                                                  0.0),
                                         new Book("The Fault in Our Stars",
                                                  "John Green",
                                                  GenreE.ROMANCE,
                                                  "A love story about two teenagers with cancer.",
                                                  true,
                                                  false,
                                                  false,
                                                  5,
                                                  5,
                                                  0.0),
                                         new Book("Gone Girl",
                                                  "Gillian Flynn",
                                                  GenreE.MYSTERY,
                                                  "A psychological thriller about a woman's disappearance.",
                                                  true,
                                                  false,
                                                  false,
                                                  4,
                                                  4,
                                                  0.0),
                                         new Book("The Hunger Games",
                                                  "Suzanne Collins",
                                                  GenreE.DYSTOPIAN,
                                                  "A dystopian novel about survival in a brutal competition.",
                                                  true,
                                                  true,
                                                  false,
                                                  7,
                                                  7,
                                                  0.0),
                                         new Book("Fahrenheit 451",
                                                  "Ray Bradbury",
                                                  GenreE.SCIENCE_FICTION,
                                                  "A novel about a future where books are banned.",
                                                  true,
                                                  false,
                                                  true,
                                                  8,
                                                  8,
                                                  0.0),
                                         new Book("Little Women",
                                                  "Louisa May Alcott",
                                                  GenreE.DRAMA,
                                                  "A novel about the lives of four sisters during the Civil War.",
                                                  true,
                                                  false,
                                                  true,
                                                  3,
                                                  3,
                                                  0.0),
                                         new Book("The Alchemist",
                                                  "Paulo Coelho",
                                                  GenreE.FANTASY,
                                                  "A philosophical novel about following one's dreams.",
                                                  true,
                                                  false,
                                                  true,
                                                  9,
                                                  9,
                                                  0.0),
                                         new Book("Dune",
                                                  "Frank Herbert",
                                                  GenreE.SCIENCE_FICTION,
                                                  "A science fiction novel about a desert planet and its resources.",
                                                  true,
                                                  false,
                                                  true,
                                                  10,
                                                  10,
                                                  0.0),
                                         new Book("The Road",
                                                  "Cormac McCarthy",
                                                  GenreE.DYSTOPIAN,
                                                  "A post-apocalyptic novel about a father and son's journey.",
                                                  true,
                                                  false,
                                                  true,
                                                  2,
                                                  2,
                                                  0.0),
                                         new Book("The Last Wish",
                                                  "Andrzej Sapkowski",
                                                  GenreE.FANTASY,
                                                  "The first book in The Witcher series, a collection of short stories introducing Geralt of Rivia.",
                                                  true,
                                                  true,
                                                  false,
                                                  10,
                                                  10,
                                                  14.99),
                                         new Book("Sword of Destiny",
                                                  "Andrzej Sapkowski",
                                                  GenreE.FANTASY,
                                                  "The second book in The Witcher series, another collection of short stories continuing Geralt's adventures.",
                                                  true,
                                                  true,
                                                  false,
                                                  10,
                                                  10,
                                                  14.99),
                                         new Book("Blood of Elves",
                                                  "Andrzej Sapkowski",
                                                  GenreE.FANTASY,
                                                  "The first novel in The Witcher saga, following Geralt's journey with Ciri.",
                                                  true,
                                                  true,
                                                  false,
                                                  10,
                                                  10,
                                                  14.99),
                                         new Book("Time of Contempt",
                                                  "Andrzej Sapkowski",
                                                  GenreE.FANTASY,
                                                  "The second novel in The Witcher saga, continuing Geralt and Ciri's story in a world of turmoil.",
                                                  true,
                                                  true,
                                                  false,
                                                  10,
                                                  10,
                                                  14.99),
                                         new Book("Baptism of Fire",
                                                  "Andrzej Sapkowski",
                                                  GenreE.FANTASY,
                                                  "The third novel in The Witcher saga, where Geralt embarks on a quest to find Ciri.",
                                                  true,
                                                  true,
                                                  false,
                                                  10,
                                                  10,
                                                  14.99),
                                         new Book("The Tower of the Swallow",
                                                  "Andrzej Sapkowski",
                                                  GenreE.FANTASY,
                                                  "The fourth novel in The Witcher saga, focusing on Ciri's journey and Geralt's struggles.",
                                                  true,
                                                  true,
                                                  false,
                                                  10,
                                                  10,
                                                  14.99),
                                         new Book("The Lady of the Lake",
                                                  "Andrzej Sapkowski",
                                                  GenreE.FANTASY,
                                                  "The fifth novel in The Witcher saga, concluding Geralt and Ciri's story in a final confrontation.",
                                                  true,
                                                  true,
                                                  false,
                                                  10,
                                                  10,
                                                  14.99));
        bookService.createAll(books);
    }

    private void initBookings() {
        List<RequestOrderDTO> orders = List.of(new RequestOrderDTO(1L, 0, true), new RequestOrderDTO(2L, 2, false));
        orderService.create(userService.getByUsername("user"), orders);
    }

    private void initPurchases() {
        List<RequestPurchaseDTO> purchases = Collections.singletonList(new RequestPurchaseDTO(1L, 2));
        purchaseService.create(userService.getByUsername("user"), purchases);
    }

    private void initReviews() {
        reviewService.create(new Review("Great book, highly recommend!", 4, userService.getByUsername("user"), bookService.getById(1L)));
    }
}