spring:
  application:
  name: nnpro-book-booking
  datasource:
    url: jdbc:postgresql://localhost:5432/book-booking
    username: bb
    password: bb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
jwt:
  secret: ${JWT_SECRET}